version: "3"
services:
  db:
    container_name: disc_db
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    container_name: disc_redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
volumes:
  db:
    driver: local
  redis:
    driver: local
