version: "3"
services:
  db:
    container_name: disc_db
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    restart: always
    container_name: disc_redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  backend:
    container_name: budget_app
    image: chloe1997/budget_app:latest
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379/
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
    volumes:
      - /root/base.yaml:/app/settings/base.yaml:ro
      - /root/production.yaml:/app/settings/production.yaml:ro
      - /root/chloepratas.com.crt:/app/chloepratas.com.crt:ro
      - /root/chloepratas.com.key:/app/chloepratas.com.key:ro
volumes:
  db:
    driver: local
  redis:
    driver: local
