application:
  port: 5000

database:
  username: "chloeadmin"
  password: "chloeadmin"
  port: 5432
  host: "localhost"
  database_name: "discord"
  require_ssl: false

redis:
  uri: "redis://localhost:6379"
  pool_max_open: 16
  pool_max_idle: 8
  pool_timeout_seconds: 1
  pool_expire_seconds: 60
